### ISSUE TITLE
Error: Expecting "-----BEGIN CERTIFICATE-----", blank line, or comment line starting with "#", got "-----BEGIN RSA PRIVATE KEY-----"

### ISSUE THREAD

**Issue by cosbor11** [dropbox/pem-converter-maven-plugin#1]
My pem has a private key and cert, it seems your plugin does not support this.

**Comment by cakoose** [comment]
Yeah, this plugin was written for X.509 certificate pinning ([Wikipedia](https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning)), but it might be easy to support other use cases.  What's your use case?

**Comment by cosbor11** [comment]
My pem was supplied by a 3rd party. It contains an RSA PRIVATE KEY and the
X.509 cert. I need to convert that pem into a jks keystore.

**Comment by cakoose** [comment]
You might be able to use a combination of OpenSSL with the JDK `keystore` tool to do this: http://stackoverflow.com/questions/2138940/import-pem-into-java-key-store).  If that works, you could try integrating those commands into your build using `exec-maven-plugin`.

It's unlikely that I'll add private key support to this plugin myself, but if you're willing to do the work, I can review your pull request.

**Comment by cosbor11** [comment]
No sweat, I just wrote a shell script and invoked it from maven.

Just giving feedback :)
